server:
  port: 6010
spring:

  # static resources
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,classpath:/public/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null